drop table if exists "user";

create table if not exists "user"
(
    id              bigint generated by default as identity
        constraint user_pk
            primary key,
    username        varchar not null,
    password        varchar not null,
    email           varchar not null,
    role            varchar not null,
    activation_code varchar
);

create unique index user_email_uindex
    on "user" (email);

create unique index user_username_uindex
    on "user" (username);

-- "user"
INSERT INTO "user" (username, password, email, role, activation_code)
-- password
VALUES ('user1', '$2a$10$h8tF9AQttfqv/FjMihPtou.dV.Fimrs0e1rCT/zBFU7I/hT4qyCvO', 'user1@example.com', 'USER', null),
       ('user2', '$2a$10$h8tF9AQttfqv/FjMihPtou.dV.Fimrs0e1rCT/zBFU7I/hT4qyCvO', 'user2@example.com', 'USER', '2222');