create table users.usr
(
    id              bigint generated by default as identity
        constraint usr_pk
            primary key,
    username        varchar not null,
    password        varchar not null,
    email           varchar not null,
    role            varchar not null,
    activation_code varchar
);

create unique index usr_email_uindex
    on users.usr (email);

create unique index usr_username_uindex
    on users.usr (username);