spring:
  application:
    name: EXAM
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: username
      password: password
      fail-fast: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/mongoDB

url:
  root: http://localhost:8765