spring:
  application:
    name: EUREKA
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: username
      password: password
      fail-fast: true

eureka:
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 10