server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          username:
          password:
          uri: https://github.com/nikita-skodin/microservice-architecture-spring-cloud-beta-4-config-storage

  application:
    name: CONFIG

  security:
    user:
      name: username
      password: password